### PR TITLE
updated package name

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
Update's the `npm` package name to `@h3/reveal`

### CODE REVIEW

**Comment by cujarrett** [comment]
@LongLiveCHIEF - Some considerations if you want:
- https://github.com/HackerHappyHour/reveal/blob/update-package-name/bower.json#L2
- README mentions and points to `.js` in name and paths

**Comment by LongLiveCHIEF** [comment]
@cujarrett not anymore!

**Comment by cujarrett** [comment]
👍

**Comment by LongLiveCHIEF** [comment]
The readme needs to be updated to use `@h3/reveal` instead of `reveal.js`, but also needs some further updates for installation and releases. It's enough changes that I think it should be its own PR.

**Pull request merged**
